### ISSUE TITLE
ModelClipMerger loses the extras information - Loses blend shape names

### ISSUE THREAD

**Issue by fire** [iimachines/Maya2glTF#108]
Applying this patch to glTF-CSharp-Loader and glTF restores the blend shape names.

https://github.com/KhronosGroup/glTF/pull/1683

**Comment by fire** [comment]
[glTFLoader.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/3709902/glTFLoader.zip)

Placing this next to the ModelClipMerger dlls also works.

**Comment by fire** [comment]
Steps to add the ModelClipMerger using the revised dlls.
```
cd src
dotnet publish .\ModelClipMerger.csproj -o ..\win64 --self-contained -r win-x64
copy replaced_binaries\win64\* ..\win64
dotnet publish .\ModelClipMerger.csproj -o ..\osx --self-contained -r osx-x64
copy replaced_binaries\osx\* ..\osx
```

How do you recommend making builds for glTF-CSharp-Loader?

**Comment by Ziriax** [comment]
Sorry I am not following, do you have problems building that lib?

**Comment by fire** [comment]
The problem is not building the library, the problem is including the entire module as a cmake external module / git repository that is fetchable from the develop branch and making the csproj work with that.

I'm not sure how that's possible.

**Comment by fire** [comment]
Closing because we're not using the merger.
