### ISSUE TITLE
Presets for Maya2glTF

### ISSUE THREAD

**Issue by fire** [iimachines/Maya2glTF#112]
I have a series of instructions for export to Godot Engine.

https://gist.github.com/fire/cc1a497b0e75da1576a0366d30a0c038

Is it reasonable to make a preset?

Any design suggestions?

**Comment by Ziriax** [comment]
Will get back to this, next two days I'm presenting my first educational web-game on a trade fair, exciting times...

**Comment by fire** [comment]
List of Quality of Life changes (QOL):

Add maya2glTF_UI to a shelf?

Keep a list of recent copyright tags.

Default the scene name to the name of the export file.

Have a button for Select menu in maya → All by Type → Geometry.

If a clip name does not exist default to the scene name.

Add a Godot default.

* Update the scale factor from 1.0 to 0.01.
* Add "-bsf -isc" to the extra flags entry field.
* Add a checkbox for "-mts" if normal maps are from Blender or are in mikktspace
* Update animation to the proper type. Defaulting to time slider

**Comment by fire** [comment]
Hope your trade show went well.

Is there an icon for a shelf?

**Comment by Ziriax** [comment]
Yes, still recovering from it ;-)

No actually we have no icon yet. 

For now, we are just using the WonderMedia logo (since this is the company that employs me and allows this exporter the be open source).

But yes, a dedicated logo should be better ;-)

https://avatars2.githubusercontent.com/u/40519170?s=110&v=4

**Comment by fire** [comment]
This is my current wireframe.

![maya2gltf_new_06](https://user-images.githubusercontent.com/32321/67812082-7695af80-fa5b-11e9-8e8f-0d9cb750ed1c.png)

It would save two clicks if the Godot preset is default, however that's two clicks more for Wonder Media.

Any suggestions on solving the problem of reducing two clicks?

**Comment by fire** [comment]
Here's another wireframe.

![maya2glTF New 11](https://user-images.githubusercontent.com/32321/67856759-7b497a80-fad2-11e9-9b75-e410f6291701.png)


Special thanks to someone helping me UX design.

**Comment by fire** [comment]
It should be possible to have two shelf icons. One for the default maya2glTF and another for Godot Engine presets.

**Comment by fire** [comment]
It's starting to take shape.

![Screen Shot 2019-10-31 at 12 47 45 PM](https://user-images.githubusercontent.com/32321/67981235-71606e00-fbdd-11e9-9537-0473669fbbd3.png)

**Comment by fire** [comment]
Here's a preset for Godot Engine:

![Screen Shot 2019-11-08 at 9 11 01 AM](https://user-images.githubusercontent.com/32321/68497666-eea56780-0209-11ea-88f5-5f56bfc8975a.png)

**Comment by fire** [comment]
Closing because I've completely forgotten the context and design for the work.
