### ISSUE TITLE
Improve error message when failing to provide the tangents of mesh

### ISSUE THREAD

**Issue by BigRoy** [iimachines/Maya2glTF#130]
### Issue

Currently whenever the exporter fails to provide the tangents for the Mesh it will just [print these errors](https://github.com/iimachines/Maya2glTF/blob/9a7faa3e70f1a2435db7cb50236683ab09c78d92/src/MeshVertices.cpp#L327):

> // Error: line 1: Maya failed to provide the tangents of mesh 'meshShape'! This should not happen, investigate your mesh //

However, it's very likely that the mesh is failing to generate tangents due to the lack of UVs for the mesh. 

**To reproduce**
This can easily be reproduced by making a new cube in Maya (in the Option Box uncheck "create UVs") and note how the error is printed when trying to do the export. And it will succeed without these errors when applying a Automatic UV mapping first or generating the cube with "create UVs" enabled.

The tangents computation being dependent on UVs was also mentioned [here](https://github.com/iimachines/Maya2glTF/issues/29#issue-332070728):

> But texture coordinates are also needed to generate tangents on the fly.

And in the [Maya API described in the `getTangents` method](https://download.autodesk.com/us/maya/2011help/API/class_m_fn_mesh.html#ec7e3c3a9ff3ff507b55fb393c5fd0f4):

> The tangent is defined as the surface tangent of the polygon running in the U direction defined by the uv map.

---

### Proposal

To improve the error message it could also print out that the problem could be related to the lack of UVs, similar to what is being [printed in the else statement](https://github.com/iimachines/Maya2glTF/blob/9a7faa3e70f1a2435db7cb50236683ab09c78d92/src/MeshVertices.cpp#L394). This could ease newcomers into finding a solution.

Additionally, I feel the message should *not* be an error but a warning to the user. This is because the export will actually succeed to perform the export however `TANGENT` attributes would just be excluded in the export.

**Comment by Ziriax** [comment]
Very nice catch.

**Comment by Ziriax** [comment]
Fixed in eaefe75f069d
