### ISSUE TITLE
Unable to dynamically load : C:/Users/dalvarez/Documents/maya/2020/plug-ins/maya2glTF.mll

### ISSUE THREAD

**Issue by 1fth3n3ls3** [iimachines/Maya2glTF#131]
Trying to use the exporter in a machine with windows 10 and getting this error in Maya 2019, Maya 2020.
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/Users/dalvarez/Documents/maya/2020/plug-ins/maya2glTF.mll

No idea what can be causing these error.

**Comment by Ziriax** [comment]
Thanks for reporting. Is the latest `rc3` release you are trying? 

Could you make a screenshot or dump of your `C:/Users/dalvarez/Documents/maya/2020/plug-ins` folder, or just tell me if `maya2glTF.mll` is in that folder?

**Comment by fire** [comment]
This is the problem with not installing the proper msvc redistributable.

**Comment by Ziriax** [comment]
Ah yes, that could be it. 

Also, the link to the msvc redistributables in the README isn't up-to-date.

The latest ones can be found [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

You most likely need [to install these](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by 1fth3n3ls3** [comment]
Thank you I will try that and will let you know. I did try in another machine and I didn't have any problem.

**Comment by 1fth3n3ls3** [comment]
It works! Thank you very much!

**Comment by Ziriax** [comment]
@fire Thank you!
