### ISSUE TITLE
Possible to be trunk based?

### ISSUE THREAD

**Issue by fire** [iimachines/Maya2glTF#132]
https://trunkbaseddevelopment.com/

The idea is that master is always the development trunk. If a stable release is done it is put into a branch like 1.0. 

Changes are always done to master and backported to for example the 1.0 branch.

**Comment by fire** [comment]
Reasoning, the default page of this project looks like it has not be maintained for 2 years.

**Comment by Ziriax** [comment]
Yep, I agree, that's the modern way, master = latest.

**Comment by fire** [comment]
I would also suggest that:

There should be a branch for each major version/tag and master. The other stale branches should be removed.

* master
* develop
* cmake_failed_pch
* cmake
* feat_sab
* dev-peter

**Comment by Ziriax** [comment]
Yes. Please note that I'm currently freelancing and just doing some maintenance fixes for IIM, the company that purchased the rights of Maya2glTF (reboot of WonderMedia Productions). So the time I can invest on this plugin is still limited, although its always fun :-)

**Comment by Ziriax** [comment]
- [x] Delete stale branches
- [ ] Merge develop into master
- [ ] Update README with latest features and build instructions
- [ ] Create 1.0 release branch

**Comment by fire** [comment]
1.1 released? :D

**Comment by fire** [comment]
I would remove master.

**Comment by Ziriax** [comment]
Yes, last thing to do.
