### ISSUE TITLE
Glb file format

### ISSUE THREAD

**Issue by 1fth3n3ls3** [iimachines/Maya2glTF#133]
When I export a maya scene i obtain several files I don't know if there is implemented somewhere in the exporter to obtain a unique Glb file where all the info is packed.

**Comment by Ziriax** [comment]
Can you try passing the `-glb` flag in the "extra flags" box of the UI?

**Comment by 1fth3n3ls3** [comment]
Just perfect! It works!

**Comment by Shoaib-Akthar** [comment]
I couldn't find extra flags. Could you please help me
![image](https://user-images.githubusercontent.com/75820991/193733047-f986af4d-1952-427f-b8f6-8993fc347782.png)

**Comment by ziriax** [comment]
Select the object you want to export.

Then in your screenshot, you can see a green glTF to Maya button, top left, in the glTF shelf.

Click it.

Then you will see the extra flags text box.

Enter -glb in it.

Click the export button.

See the readme file in this repository for all the possible flags you can type.
