### ISSUE TITLE
Cannot load plugin in Maya 2020

### ISSUE THREAD

**Issue by amiteshnandan** [iimachines/Maya2glTF#138]
After running the batch file I can see the plugins and the script folder with contents. But cannot load it in Maya 2020.

The script editor reflects this error.

loadPlugin "maya2glTF";
// Error: line 1: Unable to dynamically load : C:/Users/myname/Documents/maya/2020/plug-ins/maya2glTF.mll
The specified module could not be found.
 // 
// Error: line 1: The specified module could not be found.
 (maya2glTF) // 
updatePluginCallback();

It shows in plugin manager but of no help.

// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: Unable to dynamically load : C:/Users/myname/Documents/maya/2020/plug-ins/maya2glTF.mll
The specified module could not be found.
 // 
// Error: file: C:/Program Files/Autodesk/Maya2020/scripts/others/pluginWin.mel line 317: The specified module could not be found.
 (maya2glTF) // 

Need help. Thanks in advance.

Plugin version - maya2gltf_v1.1.0_c13125a0af77

**Comment by Ziriax** [comment]
Thanks for trying Maya2glTF!

1. Does your user name contains a space? We have a known issue that installer doesn't work correctly in that case.
2. Do you have Onedrive enabled? We modified the installer to deal with that, but it might not work on all systems.

Could you run the installer batch file and paste the output printed in the terminal?

Could you also launch Maya, and in the Script window, execute the following MEL commands:

```Python
print("MAYA_PLUG_IN_PATH="+getenv("MAYA_PLUG_IN_PATH")+"\n");
print("MAYA_SCRIPT_PATH="+getenv("MAYA_SCRIPT_PATH")+"\n");
```

and provide me the result?

**Comment by amiteshnandan** [comment]
I would love to try Maya2glTF if it runs.

Answering your questions.
1. My username does not contains space. I will paste the output below.
2. Onedrive was installed I removed it and tried running again. But same result.
********
Installer batch file output
--------------------------------------------------------------
Copying "package" to "C:\Users\amite\Documents\maya"...

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : 08 October 2020 11.56.06 AM
   Source : F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\
     Dest : C:\Users\amite\Documents\maya\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\FBX\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\Presets\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\projects\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\RSTemplates\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\scripts\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\synColor\
          *EXTRA File                191        mayaLog
          *EXTRA File             264418        shelf_Custom.mel
                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2017\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2017\presets\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2017\user.toolclips\
          *EXTRA File                  0        Maya.env
                           1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2017\plug-ins\
                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2017\prefs\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2017\prefs\hotkeys\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2017\prefs\mainWindowStates\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2017\prefs\markingMenus\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2017\prefs\scriptEditorTemp\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2017\prefs\scripts\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2017\prefs\workspaces\
          *EXTRA File                759        filePathEditorRegistryPrefs.mel
          *EXTRA File                 47        MayaInterfaceScalingConfig
          *EXTRA File               1633        menuSetPrefs.mel
          *EXTRA File                121        MTKShelf.mel
          *EXTRA File               2893        pluginPrefs.mel
          *EXTRA File                319        renderNodeTypeFavorites
          *EXTRA File                806        synColorConfig.xml
          *EXTRA File                  0        synColorConfig.xml.lock
          *EXTRA File                100        synColorFileRules.xml
          *EXTRA File                653        userNamedCommands.mel
          *EXTRA File             104348        userPrefs 2017.mel
          *EXTRA File             152923        userPrefs.mel
          *EXTRA File              12095        userRGBColors2.mel
          *EXTRA File               6450        userRunTimeCommands.mel
          *EXTRA File               6751        windowPrefs.mel
                           3    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2017\prefs\icons\
                           1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2017\prefs\shelves\
          *EXTRA File              14932        shelf_Animation.mel
          *EXTRA File              16219        shelf_Arnold.mel
          *EXTRA File               7287        shelf_Bifrost.mel
          *EXTRA File             258650        shelf_Custom.mel
          *EXTRA File                971        shelf_Custom.mel.deleted
          *EXTRA File               9860        shelf_FXCaching.mel
          *EXTRA File              15110        shelf_MASH.mel
          *EXTRA File              26925        shelf_MotionGraphics.mel
          *EXTRA File              29444        shelf_Polygons.mel
          *EXTRA File              24162        shelf_Sculpting.mel
          *EXTRA File              19678        shelf_TURTLE.mel
          *EXTRA File              33127        shelf_XGen.mel
                          11    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2017\scripts\
          *EXTRA File                640        54875202122017.arl
          *EXTRA File               1965        Glotosub.pyc
          *EXTRA File                436        How to run.txt
          New Dir          0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2018\
          New Dir          1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2018\plug-ins\
100%        New File              653824        maya2glTF.mll
          New Dir          0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2018\prefs\
          New Dir          3    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2018\prefs\icons\
100%        New File                1249        Maya2glTF.png
100%        New File                 994        Maya2glTF_ClearLogicalParents.png
100%        New File                 761        Maya2glTF_SetLogicalParent.png
          New Dir          1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2018\prefs\shelves\
100%        New File                2674        shelf_glTF.mel
          New Dir         11    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2018\scripts\
100%        New File               13730        maya2glTF_animachine.mel
100%        New File                6683        maya2glTF_assignPbrShader.mel
100%        New File               14223        maya2glTF_common.mel
100%        New File                1066        maya2glTF_createPbrSpheres.mel
100%        New File                4785        maya2glTF_exportAllScenes.mel
100%        New File                3202        maya2glTF_exportClipScenes.mel
100%        New File                1355        maya2glTF_logicalParents.mel
100%        New File                4556        maya2glTF_pasteKeyInScenes.mel
100%        New File                4323        maya2glTF_playblastClipScenes.mel
100%        New File               12151        maya2glTF_UI.mel
100%        New File                  80        maya2glTF_version.mel
                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2019\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2019\presets\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2019\user.toolclips\
          *EXTRA File                  0        Maya.env
                           1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2019\plug-ins\
                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2019\prefs\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2019\prefs\hotkeys\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2019\prefs\mainWindowStates\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2019\prefs\markingMenus\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2019\prefs\scriptEditorTemp\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2019\prefs\scripts\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2019\prefs\workspaces\
          *EXTRA File                608        filePathEditorRegistryPrefs.mel
          *EXTRA File                 47        MayaInterfaceScalingConfig
          *EXTRA File               1639        menuSetPrefs.mel
          *EXTRA File                121        MTKShelf.mel
          *EXTRA File               2765        pluginPrefs.mel
          *EXTRA File                319        renderNodeTypeFavorites
          *EXTRA File                887        synColorConfig.xml
          *EXTRA File                  0        synColorConfig.xml.lock
          *EXTRA File                320        synColorFileRules.xml
          *EXTRA File                771        userNamedCommands.mel
          *EXTRA File             144206        userPrefs.mel
          *EXTRA File               7169        userRunTimeCommands.mel
          *EXTRA File               3041        windowPrefs.mel
                           3    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2019\prefs\icons\
                           1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2019\prefs\shelves\
          *EXTRA File              16888        shelf_Animation.mel
          *EXTRA File              17911        shelf_Arnold.mel
          *EXTRA File              10301        shelf_Bifrost.mel
          *EXTRA File              37765        shelf_CurvesSurfaces.mel
          *EXTRA File               1063        shelf_Custom.mel
          *EXTRA File              30089        shelf_FX.mel
          *EXTRA File              10834        shelf_FXCaching.mel
          *EXTRA File              17017        shelf_MASH.mel
          *EXTRA File              23913        shelf_MotionGraphics.mel
          *EXTRA File              42058        shelf_Polygons.mel
          *EXTRA File              23779        shelf_Rendering.mel
          *EXTRA File              19223        shelf_Rigging.mel
          *EXTRA File              26378        shelf_Sculpting.mel
          *EXTRA File              21702        shelf_TURTLE.mel
          *EXTRA File              36347        shelf_XGen.mel
                          11    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2019\scripts\
                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2020\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2020\presets\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2020\user.toolclips\
          *EXTRA File                  0        Maya.env
                           1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2020\plug-ins\
                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2020\prefs\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2020\prefs\hotkeys\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2020\prefs\mainWindowStates\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2020\prefs\markingMenus\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2020\prefs\scriptEditorTemp\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2020\prefs\scripts\
        *EXTRA Dir        -1    C:\Users\amite\Documents\maya\2020\prefs\workspaces\
          *EXTRA File                608        filePathEditorRegistryPrefs.mel
          *EXTRA File                 47        MayaInterfaceScalingConfig
          *EXTRA File               1656        menuSetPrefs.mel
          *EXTRA File                121        MTKShelf.mel
          *EXTRA File               1093        pluginPrefs.mel
          *EXTRA File                371        renderNodeTypeFavorites
          *EXTRA File                887        synColorConfig.xml
          *EXTRA File                  0        synColorConfig.xml.lock
          *EXTRA File                320        synColorFileRules.xml
          *EXTRA File                919        userNamedCommands.mel
          *EXTRA File             157977        userPrefs.mel
          *EXTRA File               7639        userRunTimeCommands.mel
          *EXTRA File               4215        windowPrefs.mel
                           3    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2020\prefs\icons\
                           1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2020\prefs\shelves\
          *EXTRA File              16908        shelf_Animation.mel
          *EXTRA File              17367        shelf_Arnold.mel
          *EXTRA File              10301        shelf_Bifrost.mel
          *EXTRA File              37765        shelf_CurvesSurfaces.mel
          *EXTRA File             406399        shelf_Custom.mel
          *EXTRA File              17017        shelf_MASH.mel
          *EXTRA File              23904        shelf_MotionGraphics.mel
          *EXTRA File              44568        shelf_Polygons.mel
          *EXTRA File              21702        shelf_TURTLE.mel
          *EXTRA File              36347        shelf_XGen.mel
                          11    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\2020\scripts\
                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\maya2glTF\
                           0    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\maya2glTF\PBR\
                           4    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\maya2glTF\PBR\images\
                           1    F:\Amitesh\Work\Maya Plugin\maya2gltf_v1.1.0_c13125a0af77\package\maya2glTF\PBR\shaders\

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :        29         6        23         0         0        30
   Files :        69        16        53         0         0        86
   Bytes :   12.42 m   708.6 k   11.73 m         0         0    2.21 m
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00


   Speed :             1740182 Bytes/sec.
   Speed :              99.574 MegaBytes/min.
   Ended : 08 October 2020 11.56.06 AM
-----------------------------------------------------------------------------
After running the scripts in maya
------------------------------------------------------------------------------
print("MAYA_PLUG_IN_PATH="+getenv("MAYA_PLUG_IN_PATH")+"\n");
print("MAYA_SCRIPT_PATH="+getenv("MAYA_SCRIPT_PATH")+"\n");
MAYA_PLUG_IN_PATH=C:/Users/amite/Documents/maya/2020/plug-ins;C:/Users/amite/Documents/maya/plug-ins;C:/Program Files/Autodesk/Maya2020/bin/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/ATF/plug-ins;C:/Program Files/Autodesk/Bifrost/Maya2020/2.1.0.0/bifrost/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/MASH/plug-ins;C:/ProgramData/Autodesk/ApplicationPlugins/Maya2Sketchfab/Contents/plug-ins;C:/Program Files/Rokoko Motion Library/Maya/2020/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/fbx/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/camd/plug-ins;C:/Program Files/Autodesk/Arnold/maya2020/plug-ins;C:/Program Files/Allegorithmic/Substance in Maya/2020/plug-ins;C:/Program Files/Autodesk/Bifrost/Maya2020/2.1.0.0/vnn/plug-ins;C:/Program Files/Autodesk/Maya2020/plug-ins/xgen/plug-ins
MAYA_SCRIPT_PATH=C:/Users/amite/Documents/maya/projects/default/scripts;C:/Users/amite/Documents/maya/2020/scripts;C:/Users/amite/Documents/maya/scripts;C:/Users/amite/Documents/maya/2020/presets;C:/Users/amite/Documents/maya/2020/prefs/shelves;C:/Users/amite/Documents/maya/2020/prefs/markingMenus;C:/Users/amite/Documents/maya/2020/prefs/scripts;C:/Program Files/Autodesk/Maya2020/scripts;C:/Program Files/Autodesk/Maya2020/scripts/startup;C:/Program Files/Autodesk/Maya2020/scripts/shelves;C:/Program Files/Autodesk/Maya2020/scripts/others;C:/Program Files/Autodesk/Maya2020/scripts/AETemplates;C:/Program Files/Autodesk/Maya2020/scripts/unsupported;C:/Program Files/Autodesk/Maya2020/scripts/paintEffects;C:/Program Files/Autodesk/Maya2020/scripts/fluidEffects;C:/Program Files/Autodesk/Maya2020/scripts/hair;C:/Program Files/Autodesk/Maya2020/scripts/cloth;C:/Program Files/Autodesk/Maya2020/scripts/live;C:/Program Files/Autodesk/Maya2020/scripts/fur;C:/Program Files/Autodesk/Maya2020/scripts/muscle;C:/Program Files/Autodesk/Maya2020/scripts/turtle;C:/Program Files/Autodesk/Maya2020/scripts/FBX;C:/Program Files/Autodesk/Maya2020/scripts/mayaHIK;C:/Program Files/Autodesk/Maya2020/plug-ins/ATF/scripts;C:/Program Files/Autodesk/Bifrost/Maya2020/2.1.0.0/bifrost/scripts;C:/Program Files/Autodesk/Maya2020/plug-ins/MASH/scripts;C:/ProgramData/Autodesk/ApplicationPlugins/Maya2Sketchfab/Contents/scripts;C:/Program Files/Rokoko Motion Library/Maya/2020/scripts;C:/Program Files/Autodesk/Maya2020/plug-ins/fbx/scripts;C:/Program Files/Autodesk/Maya2020/plug-ins/camd/scripts;C:/Program Files/Autodesk/Arnold/maya2020/scripts;C:/Program Files/Allegorithmic/Substance in Maya/2020/scripts;C:/Program Files/Autodesk/Bifrost/Maya2020/2.1.0.0/vnn/scripts;C:/Program Files/Autodesk/Maya2020/plug-ins/xgen/scripts;C:/ProgramData/Autodesk/ApplicationPlugins/Maya2Sketchfab/Contents/shelves;C:/Program Files/Autodesk/Arnold/maya2020/scripts/mtoa/mel;
------------------------------------------------------------------------------------

I hope this helps.

**Comment by Ziriax** [comment]
That all looks fine.

Did you install the [Microsoft Visual C++ redistributables](https://go.microsoft.com/fwlink/?LinkId=746572) as stated in the README?

**Comment by amiteshnandan** [comment]
Yes, after running again it says, Its already installed.

**Comment by Ziriax** [comment]
That's weird. I tried to reproduce this by deleting my full maya folder, and installing the plug-in again, and that works for me. So something else must be going on.

Could you try installing this [alternative link](https://aka.ms/vs/16/release/vc_redist.x64.exe) and try again?

If that doesn't work, just to make sure, could you double check the plug-in is actually found at 

`C:/Users/myname/Documents/maya/2020/plug-ins/maya2glTF.mll`

Could you also give me the filesize? 

Also, maybe some anti-virus software blocked it: https://www.limilabs.com/blog/unblock-dll-file.

If nothing works, usually [dependency walker](http://www.dependencywalker.com/) is used to find out what DLLs are missing on your system, but that requires a very technical person I'm afraid.  If you want to use it, download the [x64 installer](http://www.dependencywalker.com/depends22_x64.zip), then load the `C:/Users/myname/Documents/maya/2020/plug-ins/maya2glTF.mll` file into it, wait a couple of minutes, and then `File/Save as/Comma separated values (*.csv)`, and attach that file here.

Another tool one can use is `https://www.winitor.com`.

**Comment by amiteshnandan** [comment]
The alternative link for vc_redist worked. The installation progressed and now I can load the plug-in in Maya 2020.
The plugin was there in the path. with file size 639 KB for Maya 2020. Thanks for all the help.

**Comment by Ziriax** [comment]
Thank you very much for testing! I will update the link in the README.
