### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by cgwings812** [iimachines/Maya2glTF#142]
![Error](https://user-images.githubusercontent.com/73528234/97305153-c089bf00-1882-11eb-92ec-87b3b7189eba.JPG)

Copying "package" to "C:\Users\91828\Documents\maya"...

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Tuesday, October 27, 2020 6:29:35 PM
   Source : C:\WINDOWS\system32\package\
     Dest : C:\Users\91828\Documents\maya\

    Files : *.*

  Options : *.* /S /E /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

2020/10/27 18:29:35 ERROR 2 (0x00000002) Accessing Source Directory C:\WINDOWS\system32\package\
The system cannot find the file specified.
Done. Press ENTER to exit.
Press any key to continue . . .

this error i am facing

**Comment by Ziriax** [comment]
Can you extract the installer ZIP file to your `Desktop`, e.g. in your case `C:\Users\91828\Desktop\Maya2glTF`, and run the batch file from that location? I'm not sure how you ended up extracting it in `C:\WINDOWS\system32\package`, but that folder requires administrator access.

**Comment by cgwings812** [comment]
Thank you so much for your reply. I am using your older version 1.1.0 of
Gltf exporter. It's working fine now.

[image: image.png]
Thank you so much for this tool.
