### ISSUE TITLE
If I try to export only cameras in glb format I get a damaged file.

### ISSUE THREAD

**Issue by 1fth3n3ls3** [iimachines/Maya2glTF#148]
It seems to work fine in gltf but if I add the -glb flag the file exported is corrupted or incomplete.

**Comment by Ziriax** [comment]
Thanks for reporting, that sounds like a bug, I'll look into it

**Comment by Ziriax** [comment]
This seems to be a bug in the forked COLLADA2GLTF library I'm using. I don't see a bug report in the original library about this. Need further debugging.

**Comment by Ziriax** [comment]
Aha, no, it seems a bug in my exporter, fixing...

**Comment by Ziriax** [comment]
Fixed in latest code, preparing release....

**Comment by 1fth3n3ls3** [comment]
Great I think things like this make the exporter more flesible and easy to adapt to different necessities user can have. Sadly, In my case I finally have to develope a custom solution, because of the specials needs I need to cover.
