### ISSUE TITLE
Alpha is not exporting

### ISSUE THREAD

**Issue by Spkopach** [iimachines/Maya2glTF#150]
Hey,

Ive been trying to get alpha to work on export in either GLTF or GLB. Tried by plugging in texture to the alpha on shader also even tried adjusting the alpha slide with nothing plugged in. No matter what its always fully opaque on export. 

Is there any documentation on how to get alpha to work?

Thank you!
-Sk

Maya 2019
Maya2GLTF 1.2.1

**Comment by Ziriax** [comment]
Alpha export certainly did work in the past.

I will check tomorrow if it is broken.

**Comment by Spkopach** [comment]
Awesome Thank you! Look forward to seeing what you find.

**Comment by Ziriax** [comment]
I cannot reproduce this, my transparent textures remain transparent, and show up transparent in a GLTF viewer.

Did you put your technique to `transparent` in Maya?

![image](https://user-images.githubusercontent.com/2389359/105058850-f0f28b00-5a76-11eb-8a73-3da57d59b9ea.png)

_Note that the our preview shader doesn't support transparency rendering in the viewport, for some reason Maya is not providing the correct alpha channel, not even when explicitly connecting the alpha plug to a dedicated alpha texture (e.g. and alpha of 0 can become an alpha of 1 for some reason)._

**Comment by Spkopach** [comment]
Oh I didn't see that as an option. I will try that today and get back to you on it. Thank you!

**Comment by Spkopach** [comment]
Everything is working on my side with the switch to transparent on shader side. Didn't know that option was there. So thank you for your help!
