### ISSUE TITLE
Model for AR

### ISSUE THREAD

**Issue by RepublicofNumbers** [iimachines/Maya2glTF#151]
I have an animated model exported with Maya2glTF which plays the animation in AR but when I create a simple scene with a 30 frame animation of a cube it does not play the animation in the AR environment.... I have been trying for a while to get this to work but there might be something I'm missing.

Can you help me please?    Is there a way I can send you the models ?  One of them is just a cube rotating. 

Many thanks !

**Comment by Ziriax** [comment]
Did you resolve your issue?

**Comment by RepublicofNumbers** [comment]
Hi Peter,

I did resolve the issue.

Thanks for the awesome plugin.

-Oscar

**Comment by Ziriax** [comment]
You're welcome, and thank YOU!
