### ISSUE TITLE
Parameters textures no longer showing

### ISSUE THREAD

**Issue by CodeCodeCodeCodeCodeCodeCode** [iimachines/Maya2glTF#159]
I was exporting .gltfs just fine yesterday and today when I try "assign PBR shader to selection" and select my texture files, the texture files don't show up in the Parameters section and the model looks green. 

I tried reinstalling and turning on the Plugin. Any other suggestions? 
A chocolatey doughnut for the fix.

**Comment by Ziriax** [comment]
Oh that must be a regression. What version of Maya are you using?

**Comment by Ziriax** [comment]
I can't reproduce this with the [latest release](https://github.com/iimachines/Maya2glTF/releases/tag/v1.4.0)

So I need more information. E.g. what version of Maya, version of this plugin, and maybe you could share your texture files with me?

**Comment by CodeCodeCodeCodeCodeCodeCode** [comment]
Hi, thanks for the quick response!
I'm using v1.3.1 and Maya 2019.2. I can't share my textures but they were created in Painter and exported as Redshift Roughness maps. I see the same thing though when I just use a .jpg from Google.

Here is an example of what I'm seeing (selecting just the color texture "Test_BaseColor.jpg" with the "assign PBR to selection" 
![Maya2glTF_Error_Example](https://user-images.githubusercontent.com/84748873/119505778-4e575b00-bd3b-11eb-8576-9fe2a3fa5da1.png)

**Comment by Ziriax** [comment]
I guess this previously reported issue will solve the problem:

https://github.com/iimachines/Maya2glTF/issues/146

Basically make sure that you are using OpenGL for hardware rendering.

**Comment by CodeCodeCodeCodeCodeCodeCode** [comment]
My preferences were already set to OpenGL. I tried resetting my Preferences completely too but didn't fix it. I can keep messing around and can let you know if I discover anything.

**Comment by Ziriax** [comment]
Interesting. Because the error you got `No object matches name: GLSLShader1.u_BaseColorTexture` is exactly the same as in that issue.

**Comment by Ziriax** [comment]
Can you share your texture privately?
