### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by FLASHRTX** [iimachines/Maya2glTF#170]
Hi! I have a problem with bat file. I followed the steps for installation but I can't intall the plugin. I do double clic, but I receive error 2. Please can you help me?

**Comment by Ziriax** [comment]
Can you show a screenshot?

**Comment by FLASHRTX** [comment]
![error](https://user-images.githubusercontent.com/93592330/139850713-a73ceaa6-deb4-459d-a393-3b6a29dee634.png)

**Comment by Ziriax** [comment]
It seems no files are found in `C:\Users\???\Desktop\Maya2glTF-master\maya\package\`

Maybe you have enabled `windows controlled folder access`, and unzipping to the desktop fails.

Can you list the contents of the directory `C:\Users\???\Desktop\Maya2glTF-master\maya\package\`?

PS: Note that is most likely has nothing to do with Maya2glTF, so if you have someone around of IT operations to help you out, that would be best.

**Comment by FLASHRTX** [comment]
![Sin título-2](https://user-images.githubusercontent.com/93592330/139868389-bfcc16d1-61b4-4c1f-a5f1-4faca5fd973c.png)
This is the unzipped folder. there are all the files in the zip. I tried to run the bat file as administrator, but it didn't work either.

**Comment by Ziriax** [comment]
Oh, you didn't download the correct ZIP file, you need to download a released ZIP file, you downloaded the source code ZIP file instead.

Please download and unzip [this file](https://github.com/iimachines/Maya2glTF/releases/download/v1.4.0/maya2gltf_v1.4.0_3d7ba8eaf03e.zip)

**Comment by FLASHRTX** [comment]
it works now! thanks you very much!
