### ISSUE TITLE
Mac Exporter Adds "0" character to .bin filename

### ISSUE THREAD

**Issue by psql** [iimachines/Maya2glTF#171]
![image](https://user-images.githubusercontent.com/688842/142502574-acbf8073-df9a-40d0-a5f4-9a4e95d21d80.png)
consistently adds a 0 to the end of the .bin filename. The rest of the files are fine tho!

**Comment by Ziriax** [comment]
That is by design because you can have multiple bin files. 

Of course when the exporter knows that their is only a single bin file, it could drop the suffix indeed... That might be a sensible default.

Of course you can also try to export to a `glb` file, then you get a single file.

**Comment by psql** [comment]
dropping suffix at default would be mighty handy on my end. Will try out just a glb though, good idea!

**Comment by Ziriax** [comment]
Okay, I will make this the default

**Comment by Ziriax** [comment]
See https://github.com/iimachines/Maya2glTF/releases/tag/v1.5.0 for command line argument (extra args in GUI window).

Basically just pass `-nbu` as extra argument.

Can't make this the default because might break people's scripts.
