### ISSUE TITLE
How to use transparency correctly maya2gltf

### ISSUE THREAD

**Issue by Draico01** [iimachines/Maya2glTF#187]
Hi all! I need assistance with using the transparency feature in the glsl shader in Maya from the maya2gltf plugin.

I want to create a glass with a logo on it so I have the glsl shader in transparency mode. I have placed the jpeg texture in the base color slot then have the base color factor to white and alpha to 0. In maya preview it looks fine with a transparent glass and the logo on it. The issue is now that when I test it in glTF viewer the the glass has disappeared. I have a suspicion it's the alpha but when I plug in a transparent PNG with an alpha of 1 everything is white. What am I missing in the process?

Thanks!

**Comment by ziriax** [comment]
Could you try exporting one of the transparent scenes in this repository, and see if that works for you?

**Comment by Draico01** [comment]
Apologies I am not familiar with what you are asking. I am not a coder. I just use your plugin/addon to export to glTF/glb. I can up load my files if that helps?

**Comment by ziriax** [comment]
Sorry, I forgot about this issue.

What happens if you load and expert the transparent scenes in

`https://github.com/iimachines/Maya2glTF/tree/main/maya/scenes`

**Comment by Draico01** [comment]
Hi Ziriax
I have tried what you have requested and it looks like the transparent files work. See attached.
So what am I doing incorrectly?
The logo on the glass needs to be white. But from your examples. White is the alpha. See attached for my example.

![Screen Shot 08-02-22 at 10 38 AM](https://user-images.githubusercontent.com/109980856/182331470-f64ae227-090c-472d-846b-ab443618072e.PNG)
![Screen Shot 08-02-22 at 10 39 AM 001](https://user-images.githubusercontent.com/109980856/182331482-fe280488-4d39-44ef-b32c-791f1b3bd7a3.PNG)
![Screen Shot 08-02-22 at 10 39 AM](https://user-images.githubusercontent.com/109980856/182331490-f558727a-574a-47bc-93a1-4ebf9b1d7914.PNG)

![Screen Shot 08-02-22 at 10 32 AM](https://user-images.githubusercontent.com/109980856/182330805-818afea8-f918-4cd2-9c2e-8e704a60ae83.PNG)
![Screen Shot 08-02-22 at 10 33 AM 001](https://user-images.githubusercontent.com/109980856/182330822-cf3e0aaf-28cd-4a50-8d2e-d509c59a9f78.PNG)
![Screen Shot 08-02-22 at 10 33 AM 002](https://user-images.githubusercontent.com/109980856/182330824-12196497-1db9-4a5f-9816-9374725d8940.PNG)
![Screen Shot 08-02-22 at 10 33 AM](https://user-images.githubusercontent.com/109980856/182330828-de900fb3-2b37-488a-baae-690ab33969ea.PNG)

**Comment by Draico01** [comment]
I had a closer look at the PNG file with the blue circle. I think I know what what to do but I would like to hear your info of it thanks.

**Comment by ziriax** [comment]
Hard to tell just looking at the output.

Can you share your Maya scene with me?

**Comment by Draico01** [comment]
Yes I can. I will clean it up for you as it has plenty other things.

**Comment by Draico01** [comment]
I am not sure how to share it with you but here is a wetransfer links.

https://we.tl/t-oG6fDJqXhw

**Comment by ziriax** [comment]
Sorry, I missed this issue, I was on vacation in august. 

The link is expired, can you upload this again, if still needed?

**Comment by Draico01** [comment]
I see. I was wondering why there was no response and I didn't want push.

I have figured out some of the transparency issues. I made some car lights work but I don't know how to have a label on a glass container work.
In your old versions of the plugin when I put alpha to 0 and the color to black the export shows a transparent object with full reflection on it gltf viewer etc.... Now in your new plugin when I apply the same settings the object is completely gone.

Here is my file. 

Thank you.
[Breville_Glass.zip](https://github.com/iimachines/Maya2glTF/files/9723696/Breville_Glass.zip)

**Comment by ziriax** [comment]
You can try to abuse the emissive texture I guess, so that the color of the text is added to the transparent bottle. I am not sure if this will work, but I don't think anything is wrong with the exporter in this regard, the output looks correct at first sight.

**Comment by ziriax** [comment]
No that doesn't seem to work... I'm afraid that your mesh can't work without OIT (order independent transparency). This has nothing to do with Maya2glTF, but the render engine.

Best to ask in the general GLTF rendering forums or rendering engine specific forums for how to this with GLTF and the engine.

PS: I couldn't get it any better than this, using the Babylon viewer:

![image](https://user-images.githubusercontent.com/2389359/194717748-8744fdd5-d617-4f8e-8a5a-955cfe93c384.png)

**Comment by ziriax** [comment]
See also  

https://doc.babylonjs.com/features/featuresDeepDive/materials/advanced/transparent_rendering

https://doc.babylonjs.com/features/featuresDeepDive/materials/advanced/transparent_rendering#order-independent-transparency

**Comment by Draico01** [comment]
My apologies for such a late reply. Thank you. I will have a look at the links provide. I really appreciate your help.
