### ISSUE TITLE
Maya 2023

### ISSUE THREAD

**Issue by JunkYardRobotBoy** [iimachines/Maya2glTF#188]
Hello @ziriax 

Installation seemed to work on Maya 2023 - shelf is added, plugin UI loads and I can assign PBR shaders
However on export I get this issue:
// Error: file: C:/Users/xxxx/xxxx/maya/2023/scripts/maya2glTF_UI.mel line 217: The specified procedure could not be found.
//  (maya2glTF)
Have uninstalled and re-installed multiple times and still its not working.
Any ideas on how to fix this?
Much appreciated

**Comment by ziriax** [comment]
I will try myself. I don't work for IIM anymore, I am joining NVIDIA in October, so I am not sure I will be able to install Maya 2023, due to licensing issues. But I will give it a shot.

**Comment by JunkYardRobotBoy** [comment]
Thank you @ziriax 
Best of luck at NVIDIA!

**Comment by ziriax** [comment]
I've just rebuild Maya2glTF, using a trial of Maya 2023. Seems to work out of the box. Can you test? See attached file

[Maya2glTF-2023.zip](https://github.com/iimachines/Maya2glTF/files/9540338/Maya2glTF-2023.zip)

**Comment by JunkYardRobotBoy** [comment]
@ziriax Sir you are an absolute superstar!
Works really well. Thank you very much!

**Comment by BigRoy** [comment]
I suspect this issue can be closed now.

**Comment by Shoaib-Akthar** [comment]
Could any one help me how to export to glb
