### ISSUE TITLE
Materials not displayed correctly in maya

### ISSUE THREAD

**Issue by adwordsjamesK** [iimachines/Maya2glTF#195]
Hi
I install the plugin through the installation steps.After selecting the material(glTF_PBR.ogsfx).Materials not displayed correctly.But does not reflect IBL effects. Material is displayed in black.
Many thanks.

**Comment by adwordsjamesK** [comment]
This is my effect.
![696C9AE6-EF12-4157-8B13-E97FC5D0DF22](https://user-images.githubusercontent.com/87850976/225799748-656cce81-26d5-4f05-975f-4f81bbcbfb74.jpeg)

**Comment by ziriax** [comment]
Oh you closed the issue already? Did you find a solution?
