### ISSUE TITLE
Document process for packaging builds

### ISSUE THREAD

**Issue by fire** [iimachines/Maya2glTF#88]
What is the process for generating an install-able build?

**Comment by Ziriax** [comment]
For Windows, I have a new batch file coming up, I will commit this in the `develop` branch.

The one in master is https://raw.githubusercontent.com/WonderMediaProductions/Maya2glTF/master/windows_make_release.cmd

Needs cleanup, I would prefer to use `cmake` to do all this, or some other cross platform approach...

**Comment by fire** [comment]
Wrote some cmake in https://github.com/WonderMediaProductions/Maya2glTF/pull/102

The naming of the bat files and version needs review.

**Comment by fire** [comment]
I think this is done.
