### ISSUE TITLE
Document how to use merger tool

### ISSUE THREAD

**Issue by fire** [iimachines/Maya2glTF#99]
Requires: 

1. a gltf with no animations to be the rig
2. several gltfs with a clip (can there be more than one clip?)
3. Run the dll via `dotnet WonderMedia.glTF.ModelClipMerger.dll`
2. clips with the same name are overwritten in some order.

Currently there's a hard coded path too.

**Comment by Ziriax** [comment]
Well, I would have to figure it out myself again, it has been a while since I worked on this ;-)

**Comment by fire** [comment]
I figured it out, but we're not using it. So closing bug.
